Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 120
Style/RedundantParentheses:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

